name: MLOps Pipeline

on: [push, pull_request]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Train model
        run: |
          source venv/bin/activate
          python main.py --train

      - name: Evaluate model
        run: |
          source venv/bin/activate
          python main.py --evaluate

      - name: Push Docker image
        if: success()
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t amenihosni/mlops-app .
          docker tag amenihosni/mlops-app amenihosni/mlops-app:latest
          docker push amenihosni/mlops-app:latest

