name: MLOps Pipeline

on: [push, pull_request]

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Initialize virtual environment
        run: |
          python -m venv venv
          echo "VENV_PATH=$(pwd)/venv" >> $GITHUB_ENV

      - name: Install project dependencies
        run: |
          source $VENV_PATH/bin/activate
          make install

      - name: Data preparation
        run: |
          source $VENV_PATH/bin/activate
          make prepare

      - name: Code quality checks
        run: |
          source $VENV_PATH/bin/activate
          make lint

      - name: Model training
        run: |
          source $VENV_PATH/bin/activate
          make train || exit 1

      - name: Model evaluation
        run: |
          source $VENV_PATH/bin/activate
          make evaluate

      - name: Run tests
        run: |
          source $VENV_PATH/bin/activate
          make test

      - name: Model verification
        run: |
          make check-model

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ml-artifacts
          path: |
            model.joblib
            mlruns/
