name: MLOps Pipeline

on: [push, pull_request]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Train model
        run: |
          source venv/bin/activate
          python main.py --train

      - name: Evaluate model
        run: |
          source venv/bin/activate
          python main.py --evaluate

      - name: Run MLflow UI
        run: |
          source venv/bin/activate
          nohup python -m mlflow ui --host 0.0.0.0 --port 5000 &
          sleep 2 && xdg-open http://127.0.0.1:5000 || start http://127.0.0.1:5000 || open http://127.0.0.1:5000
