name: MLOps Pipeline

on: [push, pull_request]

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest

      - name: Prepare data
        run: |
          source venv/bin/activate
          python main.py --prepare churn-bigml-80.csv

      - name: Run linters
        run: |
          source venv/bin/activate
          flake8 *.py
          black --check *.py

      - name: Train model
        run: |
          source venv/bin/activate
          python main.py --train

      - name: Evaluate model
        run: |
          source venv/bin/activate
          python main.py --evaluate

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/ -v

      - name: Save model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: model.joblib
