name: MLOps Pipeline

on: [push, pull_request]

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug files
        run: ls -al

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Create and activate venv
        run: |
          python -m venv venv
          echo "VENV_PATH=$(pwd)/venv" >> $GITHUB_ENV
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source $VENV_PATH/bin/activate
          pip install -r requirements.txt

      - name: Prepare data
        run: |
          source $VENV_PATH/bin/activate
          python main.py --prepare churn-bigml-80.csv

      - name: Train model
        run: |
          source $VENV_PATH/bin/activate
          python main.py --train || exit 1

      - name: Validate model
        run: |
          if [ ! -f model.joblib ]; then
            echo "::error::Model file not found!"
            exit 1
          fi
          ls -lh model.joblib

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ml-artifacts
          path: |
            model.joblib
            mlruns/
