name: MLOps Pipeline

on: [push, pull_request]

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install project dependencies
        run: make install

      - name: Prepare data
        run: make prepare

      - name: Run code quality checks
        run: make lint

      - name: Train model
        run: make train

      - name: Evaluate model
        run: make evaluate

      - name: Run tests
        run: make test

      - name: Start MLflow tracking
        run: make run-mlflow
        continue-on-error: true  # Permet au workflow de continuer même si MLflow reste actif

      - name: Verify model existence
        run: make check-model

      - name: Upload trained model
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: model.joblib
