name: MLOps Pipeline

on: [push, pull_request]

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install project dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare data
        run: |
          source venv/bin/activate
          make prepare

      - name: Lint code
        run: |
          source venv/bin/activate
          make lint

      - name: Train model
        run: |
          source venv/bin/activate
          make train

      - name: Evaluate model
        run: |
          source venv/bin/activate
          make evaluate

      - name: Run tests
        run: |
          source venv/bin/activate
          make test

      - name: Validate model artifact
        run: |
          if [ ! -f model.joblib ]; then
            echo "❌ Model file not found!"
            exit 1
          fi

      - name: Upload model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: model.joblib
